Projekt-StudieTips/Controllers/ModeratorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using Projekt_StudieTips.Repository;
using System;
using System.Threading.Tasks;

namespace Projekt_StudieTips.Controllers
{
    [Authorize(Policy = "IsModerator")]

    public class ModeratorController : Controller
    {

        private readonly ITipRepository _repository;


        public ModeratorController(ITipRepository repository)
        {
            _repository = repository;
        }


        // GET: ModeratorController
        public async Task<IActionResult> Index(string sortOrder, int? page)
        {
            var context = await _repository.GetUnmoderatedTips();

            ViewBag.DateSortParm = sortOrder == "date_desc" ? "date_desc" : "date_asc";

            try
            {
                if (context.Count == 0)
                {
                    ViewBag.CourseName = "Der er ingen tips at verificere.";
                }
            }
            catch (InvalidOperationException)
            {
                return NotFound();
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            if (pageNumber < 1)
            {
                pageNumber = 1;
            }


            return View(context.ToPagedList(pageNumber, pageSize));
        }



        public async Task<IActionResult> VerifyTip(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var tip = await _repository.GetTip(id);
            if (tip == null)
            {
                return NotFound();
            }

            tip.IsVerified = true;

            _repository.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DenyTip(int id)
        {

            await _repository.DeleteTip(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-StudieTips/Views/Moderator/Index.cshtml
@*@model IEnumerable<Projekt_StudieTips.Models.Tip>*@
@using PagedList
@model PagedList.IPagedList<Projekt_StudieTips.Models.Tip>
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/css/tippage.css" />
@using PagedList.Mvc;

@{
    ViewData["Title"] = "Index";
}


@{
    var courseName = ViewBag.CourseName;
    var courseId = ViewBag.CourseId;
}

<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>



<body class="text-center">
    @if (courseName != null)
    {
        <div class="text-center">
            <h1 class="h1Degree" style="font-size: 6em">@courseName </h1>
        </div>
    }
    else
    {
        <div class="text-center">
            <h1 class="h1Degree" style="font-size: 6em">Verificér tips </h1>
        </div>
    }


    <label for="sort" class="h1Degree" style="font-size: 2em"></label>
    <form action="" class="select CenterEverything" style="transform: scale(0.5)">
        <select name="sortOrder" id="sortOrder" onchange="this.form.submit()">
            <option selected disabled>Sortér...</option>
            <option value="date_desc">Nyeste først</option>
            <option value="date_asc">Ældste først</option>
        </select>
    </form>


    @* Bruger class=mx-auto for at centrere indholdet *@
    <div class="mx-auto widthclass" style="text-align: center;">
        @foreach (var item in Model)
        {

            var text = item.Text;
            var textLength = text.Length;
            var first = "";
            var end = "";
            var rmLength = 40;

            if (textLength >= rmLength)
            {
                first = text.Substring(0, rmLength);
                end = text.Substring(rmLength);
            }
            else
            {
                first = text.Substring(0, textLength);

            }

            <div class="post" name="postdiv" style="overflow-wrap: break-word">
                <div>
                    <p style="font-size: 1.2em; color:rgba(10,141,255,1.0)">
                        Bruger: @item.Username
                    </p>


                    <p style="float: top; font-size: 1em; color:#000">
                        @Html.DisplayFor(modelItem => item.Date)
                    </p>

                </div>

                <div class="topright">
                    <p class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Moderator" asp-route-id="@item.TipId" asp-action="VerifyTip" style="font-size: 1.5em">Verificér</a>
                    </p>
                </div>
                <div class="topright">
                    <p class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Moderator" asp-route-id="@item.TipId" asp-action="DenyTip" style="font-size: 1.5em">Fjern</a>
                    </p>
                </div>



                <div class="tiptext2">
                    <p style="font-size: 1.8em; color: #000;">
                        @Html.DisplayFor(modelItem => item.Headline)
                    </p>
                </div>

                <div class="tiptext3" style="font-size: 1.3em">
                    @if (textLength >= rmLength)
                    {
                        @(first)<span class="dots">...</span><span class="more">@(end)</span>
                        <button class="read">Vis mere...</button>
                    }
                    else
                    {
                        @(first)
                    }
                </div>
            </div>




        }
        <div class="h1Degree" style="font-size: 2em;">
            Side @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) ud af @Model.PageCount


            @if (Model.PageNumber > 1)
            {
                <p class="nav-item" style="float:left">
                    @{ var previousPage = Model.PageNumber - 1;}
                    <a class=" text-white" asp-area="" asp-controller="Moderator" asp-route-sortOrder="ViewBag.DateSortParm" asp-route-page="@previousPage" asp-route-id="@courseId" asp-action="Index">Forrige</a>
                </p>
            }
            @if (Model.PageNumber < Model.PageCount)
            {
                <p class="nav-item" style="float:right">
                    @{ var nextPage = Model.PageNumber + 1;}
                    <a class=" text-white" asp-area="" asp-controller="Moderator" asp-route-sortOrder="ViewBag.DateSortParm" asp-route-page="@nextPage" asp-route-id="@courseId" asp-action="Index">Næste</a>
                </p>
            }
        </div>


    </div>


    @*Javascript der håndterer read more / read less collapse-funktionen på tips*@
    <script>
        $(document).ready(function () {
            $(".read").click(function () {
                $(this).prev().toggle();
                $(this).siblings('.dots').toggle();
                if ($(this).text() === 'Vis mere...') {
                    $(this).text('Vis mindre...');
                } else {
                    $(this).text('Vis mere...');
                }
            });
        });
    </script>


</body>
</html>